// Connect the HTML elements to the Script
const dropZone = document.getElementById('drop-zone');
const fileInput = document.getElementById('evidenceInput');

// 1. CLICK TO BROWSE
dropZone.addEventListener('click', () => {
    console.log("Box clicked!");
    fileInput.click();
});

// 2. DRAG AND DROP LOGIC
// We have to tell the browser NOT to just open the file in the tab
['dragenter', 'dragover', 'dragleave', 'drop'].forEach(eventName => {
    dropZone.addEventListener(eventName, (e) => e.preventDefault());
});

dropZone.addEventListener('dragover', () => dropZone.classList.add('active'));
dropZone.addEventListener('dragleave', () => dropZone.classList.remove('active'));

dropZone.addEventListener('drop', (e) => {
    dropZone.classList.remove('active');
    const files = e.dataTransfer.files;
    if (files.length > 0) processEvidence(files[0]);
});

fileInput.addEventListener('change', (e) => {
    if (e.target.files.length > 0) processEvidence(e.target.files[0]);
});

// 3. GENERATE CRYPTOGRAPHIC HASH
async function processEvidence(file) {
    console.log("Processing:", file.name);
    document.getElementById('status').innerText = "Hashing " + file.name + "...";
    
    const arrayBuffer = await file.arrayBuffer();
    const hashBuffer = await crypto.subtle.digest("SHA-256", arrayBuffer);
    const hashArray = Array.from(new Uint8Array(hashBuffer));
    const hashHex = hashArray.map(b => b.toString(16).padStart(2, '0')).join('');

    document.getElementById('status').innerText = "Seal Verified.";
    document.getElementById('result').innerHTML = `
        <div style="background: #1a1c23; padding: 20px; border: 1px solid #00ff88; margin-top: 20px; border-radius: 8px;">
            <p style="font-size: 0.7rem; color: #8b949e;">SHA-256 FINGERPRINT</p>
            <code style="word-break: break-all; color: #00ff88;">${hashHex}</code>
            <button onclick="downloadReport('${file.name}', '${hashHex}')" class="btn-download">Download Rule 901(c) Report</button>
        </div>
    `;
}

// 4. DOWNLOAD PDF
function downloadReport(name, hash) {
    const date = new Date().toLocaleString();
    const env = navigator.userAgent; // Captures the browser/OS for the forensic trail

    // The "Content" that goes inside the PDF
    const content = `
        <div style="padding: 50px; font-family: 'Times New Roman', serif; color: #000; line-height: 1.6;">
            <h1 style="text-align: center; border-bottom: 2px solid #000; padding-bottom: 10px;">
                JURISPRUVE INTEGRITY REPORT
            </h1>
            <p style="text-align: right;"><strong>Date of Intake:</strong> ${date}</p>
            
            <section style="margin-top: 30px;">
                <h3>EVIDENCE IDENTIFICATION</h3>
                <p><strong>File Name:</strong> ${name || "Unknown File"}</p>
                <p><strong>Cryptographic Fingerprint (SHA-256):</strong></p>
                <p style="font-family: monospace; background: #f4f4f4; padding: 15px; border: 1px solid #ccc; word-break: break-all;">
                    ${hash || "No Hash Generated"}
                </p>
            </section>

            <section style="margin-top: 30px;">
                <h3>AUTHENTICATION STATEMENT</h3>
                <p>Pursuant to <strong>Federal Rule of Evidence 901(c)</strong>, this report certifies that the electronic data 
                described above has been processed via the Jurispruve Integrity Protocol. The process used to generate 
                this hash is a standard cryptographic function that produces a unique digital fingerprint. 
                Any modification to the original file will result in a different hash value, providing a 
                verifiable method of authentication.</p>
            </section>

            <section style="margin-top: 30px; font-size: 0.8rem; color: #555;">
                <p><strong>Collection Environment:</strong> ${env}</p>
            </section>
            
            <footer style="margin-top: 50px; border-top: 1px solid #eee; padding-top: 10px; font-style: italic;">
                Generated by Jurispruve Protocol v1.0
            </footer>
        </div>`;

    // Configuration for the PDF generator
    const opt = {
        margin:       0.5,
        filename:     `Jurispruve_Report_${name}.pdf`,
        image:        { type: 'jpeg', quality: 0.98 },
        html2canvas:  { scale: 2 },
        jsPDF:        { unit: 'in', format: 'letter', orientation: 'portrait' }
    };

    // Run the conversion
    html2pdf().set(opt).from(content).save();
}
